# Generated by Django 4.1.4 on 2023-05-13 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloner', '0005_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='chirp_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
