# Generated by Django 4.1 on 2023-05-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloner', '0006_chirp_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
